language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install multiresolcp 

# command to run tests
script:
  - py.test tests/test.py 
